# Generated by Django 2.2.28 on 2022-10-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_qasdfgh'),
    ]

    operations = [
        migrations.AddField(
            model_name='qasdfgh',
            name='sdyuiuytrewq',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
